# General Configuration
version: 1.1.0.{build}
skip_branch_with_pr: true

# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  #init and update submodules
  - git submodule update --recursive --init

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'


# Build Configuration
platform: Any CPU
configuration: Release


before_build:
  - nuget restore

build:  
  publish_nuget: true
  project: SpeckleCoreGeometry.sln
  verbosity: minimal

after_build:
# remove garbage
  - ps: |
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\x86" -Recurse -ErrorAction Ignore
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\x64" -Recurse -ErrorAction Ignore
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\*.pdb" -Recurse -ErrorAction Ignore
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\SpeckleCoreGeometry.dll.config" -Recurse -ErrorAction Ignore
 # zip everything into a zip file containing package folder structure
  - 7z a SpeckleCoreGeometry.zip "%APPVEYOR_BUILD_FOLDER%\SpeckleCoreGeometry\bin\Release\*"

artifacts:
  - path: SpeckleCoreGeometry.zip
    name: Release

#deploy to nuget
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: n4EiHDLVSLjOzqT7OOOg3US3PWs6fNsOaGpyT/EFBKrTKl/1wMmmKt73MNuTngD+
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
  on:
    branch: nuget